name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build the Docker image
      run: docker build . --build-arg build_date=$(date +'%Y-%m-%d') --file Dockerfile --tag jreissup/ubuntu-base
    - name: Docker Push
      run: docker push jreissup/ubuntu-base
